### ISSUE TITLE
Undefined reference error after `pf_initialize`

### ISSUE THREAD

**Issue by femtomc** [probcomp/GenParticleFilters.jl#5]
I'm not sure if this is related to unsplatting and assigning into `state.new_traces`.

Offending code:

```julia
    state = pf_initialize(gen_fn.model, model_args[1], 
                          observations[1], gen_fn.initial_proposal,
                          proposal_args[1], num_particles)
    for t in 2 : length(observations)
        pf_multinomial_resample!(state)
        pf_update!(state, model_args[t], argdiffs[t], 
                   observations[t], 
                   gen_fn.transition_proposal, proposal_args[t])
    end
```

this occurs on the first iteration:

```
ERROR: LoadError: UndefRefError: access to undefined reference
Stacktrace:
 [1] indexed_iterate(t::Tuple{Main.GenSMCGFTests.var"##StaticIRTrace_line_model#312", Float64, Gen.UnknownChange, Gen.StaticChoiceMap{(), Tuple{}, (:line,), Tuple{Gen.DynamicChoiceMap}}}, i::Int64, state::Int64)
   @ Base ./tuple.jl:89
 [2] pf_update!(state::Gen.ParticleFilterState{Main.GenSMCGFTests.var"##StaticIRTrace_line_model#312"}, new_args::Tuple{Int64}, argdiffs::Tuple{}, observations::Gen.DynamicChoiceMap, proposal::Gen.DynamicDSLFunction{Any}, proposal_args::Tuple{Int64})
   @ GenParticleFilters ~/.julia/packages/GenParticleFilters/zYKP1/src/update.jl:82
```

I looked inside `pf_initialize` -- and it seems like `state.new_traces` and `state.traces` are both initialized there, so this is slightly vexing.

**Comment by femtomc** [comment]
The reference code in lib is: https://github.com/probcomp/GenParticleFilters.jl/blob/053e8c9b382f58b5a5c61e3ad0094daad5696268/src/update.jl#L82-L83

**Comment by femtomc** [comment]
Is this related to https://github.com/JuliaLang/julia/issues/43783#issuecomment-1048909305?

**Comment by femtomc** [comment]
Yes, this is generic -- it fails for tests in `GenParticleFilters` with the same issue.

I think it's definitely related to the above (regression in Julia > 1.7).

**Comment by ztangent** [comment]
Resolved upstream: https://github.com/probcomp/Gen.jl/issues/450
